Add temp fix to lease statistic report
Some contract rents of leases don't have set period type so the data
enrichment crashes to the monthly amount calculations. This is
a temporary fix which ignores all the leases where the period type is
missing from the contract rents.

Exception: NotImplementedError: Cannot calculate monthly amount for
PeriodType None